### ISSUE TITLE
Issue: Npm Package Not Published to NPM Js.

### ISSUE THREAD

**Issue by PranuPranav97** [gopalanand333/nodejs-unique-numeric-ID-generator#16]
Hi Gopal Anand,
The package is been published to npmjs registry for the new updates.
Thanks

**Comment by gopalanand333** [comment]
@PranuPranav97 
thanks for your contribution. I have published the new version to npm.
https://github.com/gopalanand333/nodejs-unique-numeric-ID-generator/releases/tag/Release 

Regards,
Gopal
